- name: Copy artifact
  copy:
    src: artifact.tar.gz
    dest: ~/artifact.tar.gz

- name: Extract files
  command: tar -xf artifact.tar.gz

- name: Change directory
  command: chdir=backend {{ item }}
  with_items:
    - npm install
    - pm2 stop default
    - pm2 start npm -- start
