- name: Copy artifact
  copy:
    src: artifact.tar.gz
    dest: ~/artifact.tar.gz

- name: Extract files
  command: tar -xf artifact.tar.gz

- name: Change directory
  command: cd backend

- name: Install npm
  command: npm install

- name: Stop PM2
  command: pm2 stop default

- name: Start PM2
  command: pm2 start npm -- start
