- name: Copy artifact
  copy:
    src: artifact.tar.gz
    dest: ~/artifact.tar.gz

- name: Extract files
  command: |
    cd ~
    tar -xf artifact.tar.gz

- name: Run node server
  command: |
    cd backend
    npm install
    pm2 stop default
    pm2 start npm -- start
